<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>lab5</AssemblyName>
    <RootNamespace>lab5</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\lab5.Core\lab5.Core.csproj" />
  </ItemGroup>
</Project>
